### ISSUE TITLE
How to deal with the problem of "Error code:1001"?

### ISSUE THREAD

**Issue by wjiafan** [darkerego/blitzkloud#1]
###  'Payload.py' output info:

error code: 1001
Base64 error: Invalid base64-encoded string: length cannot be 1 more than a multiple of 4
Invalid base64-encoded string: length cannot be 1 more than a multiple of 4
Error: 'NoneType' object has no attribute 'lstrip'
can only concatenate str (not "NoneType") to str
Reconnecting in 7 seconds ... 

### 'Payload.py'  configuration

code around line 1234.....

debug = True
front_host = 'digininja.org' 
url = 'gg.~~.xyz:8880'  
host_header = str('Host: %s' % front_host)
key = b"This_key_for_demo_purposes_only!" 

###  value 
front_host = ??

command:   
    curl -s -H 'Host: digininja.org' http://gg.~~.xyz:80
    curl -s -H 'Host: digininja.org' http://gg.~~.xyz:8880

output info:

**C:\Users\~~\Desktop\tools>curl -s -H 'Host: digininja.org' http://gg.~~xyz:80**

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**C:\Users\~~\Desktop\tools>curl -s -H 'Host: digininja.org' http://gg.~~.xyz:8880**
```
<html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```

**Comment by darkerego** [comment]
The site you're trying to reach (digininja.org) is not hosted on Cloudlfare... so, no that is not going to work. It is an infinite redirect error, they probably use SNI but yeah that is not going to work.
